#!/usr/bin/env bash
[ -z "$FIFO_UEBERZUG" ] && exit
readonly ID_PREVIEW="preview"

if [ "$1" = "draw" ]; then
	declare -p -A cmd=([action]=add [identifier]="$ID_PREVIEW" [x]=$2 [y]=$3 [width]=$4 [height]=$5 [path]="$PWD/$6") > "$FIFO_UEBERZUG"
	#echo "{\"action\": \"add\", \"identifier\": \""$ID_PREVIEW"\", \"x\": "$2", \"y\": "$3", \"width\": "$4", \"height\": "$5", \"path\":I\""${PWD}/$6"\"}" > "$FIFO_UEBERZUG"
else
	declare -p -A cmd=([action]=remove [identifier]="$ID_PREVIEW") > "$FIFO_UEBERZUG"
fi
