#!/bin/bash
#Toggles rotation.
#Unfortunately will not work with multi screens yet.
#Used for x200t rotate screen button so I have no needs for multi screens.

if xrandr | grep LVD | grep --quiet "right ("
then 
		xrandr -o normal
		xsetwacom set "Serial Wacom Tablet WACf004 stylus" rotate none
		xsetwacom set "Serial Wacom Tablet WACf004 eraser" rotate none
else 
		xrandr -o right
		xsetwacom set "Serial Wacom Tablet WACf004 stylus" rotate cw
		xsetwacom set "Serial Wacom Tablet WACf004 eraser" rotate cw
fi
