#!/bin/bash
#Toggles rotation.
#Unfortunately will not work with multi screens yet.
#Used for x200t rotate screen button so I have no needs for multi screens.

if xrandr | grep LVD | grep --quiet "right ("
then xrandr -o normal
else xrandr -o right
fi
