#!/usr/bin/env bash
[ -z "$FIFO_UEBERZUG" ] && exit
readonly ID_PREVIEW="preview"

if [ "$1" = "imgpreview" ]; then
        declare -p -A cmd=([action]=add [identifier]="$ID_PREVIEW" [x]=$2 \
            [y]=$3 [width]=$4 [height]=$5 [path]="$PWD/$6" [scaler]="contain" [synchronously_draw]=false) > "$FIFO_UEBERZUG"
elif [[ "$1" == "pdfpreview" ]]; then
        tempdir="/tmp/pdfpreview"
        [[ ! -d $tempdir ]] && mkdir -p $tempdir
        [[ ! -f "$tempdir/$6.jpg" ]] && pdftoppm -jpeg -singlefile "$6" "$tempdir/$6"
        [[ -f "$tempdir/$6.jpg" ]] && declare -p -A cmd=([action]=add \
        [identifier]="$ID_PREVIEW" [x]="$2" [y]="$3" [width]="$4" \
        [height]="$5" [path]="$tempdir/$6.jpg") \
            > "$FIFO_UEBERZUG"
else
        declare -p -A cmd=([action]=remove [identifier]="$ID_PREVIEW") > "$FIFO_UEBERZUG"
fi
